HaxePunk/HaxePunk

.gitignore, haxepunk2d/utils/ArrayUtils.hx, haxepunk2d/utils/Time.hx
I added named time flags (Usage example: http://git.io/bB9aJg) and made some small changes.
=> Release 3.0.0

com/haxepunk/Tween.hx, com/haxepunk/graphics/BitmapText.hx, com/haxepunk/graphics/ParticleType.hx
Namely for Tweens, BitmapText and fixed an error in ParticleType.
=> Added and clarified some documentation

.travis.yml, com/haxepunk/graphics/Graphiclist.hx
Receives and index as a parameter, and returns the Graphic positioned at said index in the array _graphics. If the index is less than zero or greater or equal than the array length, it throws "Index out of bounds".
=> Added a get function for class Graphiclist

com/haxepunk/graphics/Backdrop.hx, com/haxepunk/masks/Grid.hx, com/haxepunk/masks/Imagemask.hx, com/haxepunk/masks/Pixelmask.hx, com/haxepunk/tweens/sound/SfxFader.hx, tools/Run.hx
Addresses #389 ; #390 now redundant
=> Fix Run.hx for Haxe >= 3.3.0 ; fix backdrop issue with screen scaling

com/haxepunk/Graphic.hx, com/haxepunk/graphics/Emitter.hx, com/haxepunk/graphics/Particle.hx, com/haxepunk/graphics/ParticleType.hx, com/haxepunk/graphics/atlas/AtlasData.hx, com/haxepunk/graphics/atlas/AtlasRegion.hx, com/haxepunk/graphics/atlas/BitmapFontAtlas.hx, com/haxepunk/utils/Ease.hx
This adds scale, rotation, and trails to particles and removes duplicate rendering logic by reusing Image/Spritemap for rendering. Also fixes a bug where paused particles would continue moving indefinitely. Shouldn't have any breaking changes.
=> Emitter improvements.

.travis.yml, com/haxepunk/Engine.hx, com/haxepunk/HXP.hx, com/haxepunk/Screen.hx, com/haxepunk/graphics/atlas/Renderer.hx, com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx, com/haxepunk/screen/FixedScaleMode.hx, com/haxepunk/screen/ScaleMode.hx, com/haxepunk/screen/UniformScaleMode.hx, com/haxepunk/utils/Platform.hx, include.xml, tests/src/TestSuite.hx, tests/src/com/haxepunk/ScreenTest.hx, tests/src/com/haxepunk/screen/FixedScaleModeTest.hx, tests/src/com/haxepunk/screen/UniformScaleModeTest.hx, tests/test-nme.hxml, tests/test-openfl3.hxml, tests/test-openfl4.hxml
=> Screen scale modes

com/haxepunk/graphics/Text.hx
Part of some changes to Text.hx, This adds the ability to have different filters on your text.
=> Added BitmapFilter Array to TextOptions

com/haxepunk/Engine.hx, com/haxepunk/Scene.hx, com/haxepunk/graphics/atlas/DrawCommand.hx, com/haxepunk/graphics/atlas/HardwareRenderer.hx, com/haxepunk/graphics/atlas/SceneSprite.hx
Draw a colored and optionally semi-transparent background for each scene, with lower scenes on the stack drawn behind. Replaces the `transparent` flag.
=> Replace Scene.transparent with Scene.color and Scene.alpha.

haxepunk/graphics/Text.hx
=> Set modified TextFormat after Text changes (#435)

haxepunk/Camera.hx, haxepunk/Engine.hx, haxepunk/Entity.hx, haxepunk/HXP.hx, haxepunk/Position.hx, haxepunk/RenderMode.hx, haxepunk/Scene.hx, haxepunk/Screen.hx, haxepunk/graphics/BitmapText.hx, haxepunk/graphics/ColoredRect.hx, haxepunk/graphics/Emitter.hx, haxepunk/graphics/Image.hx, haxepunk/graphics/Text.hx, haxepunk/graphics/Tilemap.hx, haxepunk/graphics/atlas/AtlasData.hx, haxepunk/graphics/atlas/AtlasRegion.hx, haxepunk/graphics/atlas/BaseShader.hx, haxepunk/graphics/atlas/DrawCommand.hx, haxepunk/graphics/atlas/DrawCommandBatch.hx, haxepunk/graphics/atlas/GLUtils.hx, haxepunk/graphics/atlas/HardwareRenderer.hx, haxepunk/graphics/atlas/SceneSprite.hx, haxepunk/utils/Color.hx, haxepunk/utils/MathUtil.hx
Smarter inlining, significantly reduced GC activity, and restructured HardwareRenderer to be more clear.
=> Rendering GC/performance optimizations

doc/Main.hx, doc/theme/templates/nav.mtt
This fixes api navigation so we don't skip the first level package. Also, it seems that dox requires a static main.
=> Fixing api nav generation

haxepunk/AssetManager.hx, haxepunk/Entity.hx, haxepunk/Graphic.hx, haxepunk/Scene.hx, haxepunk/Tweener.hx, haxepunk/graphics/Backdrop.hx, haxepunk/graphics/BitmapText.hx, haxepunk/graphics/ColoredRect.hx, haxepunk/graphics/Emitter.hx, haxepunk/graphics/Image.hx, haxepunk/graphics/NineSlice.hx, haxepunk/graphics/TiledImage.hx, haxepunk/graphics/TiledSpritemap.hx, haxepunk/graphics/Tilemap.hx, haxepunk/graphics/atlas/Atlas.hx, haxepunk/graphics/atlas/AtlasData.hx, haxepunk/graphics/atlas/AtlasRegion.hx, haxepunk/graphics/atlas/AtlasResolutions.hx, haxepunk/graphics/atlas/BitmapFont.hx, haxepunk/graphics/atlas/BitmapFontAtlas.hx, haxepunk/graphics/atlas/DrawCommand.hx, haxepunk/graphics/atlas/DrawCommandBatch.hx, haxepunk/graphics/atlas/GlyphData.hx, haxepunk/graphics/atlas/HardwareRenderer.hx, haxepunk/graphics/atlas/IAtlasRegion.hx, haxepunk/graphics/atlas/IBitmapFont.hx, haxepunk/graphics/atlas/SceneSprite.hx, haxepunk/graphics/atlas/TextureAtlas.hx, haxepunk/utils/MathUtil.hx
Currently this can require a lot of extra memory - need a better way to lazy load textures/dispose of them when no longer needed.
=> Multiple resolution images and bitmap fonts

haxepunk/graphics/BitmapText.hx, haxepunk/graphics/Text.hx
&lt;left>, &lt;center> and &lt;right> format tags.
=> BitmapText alignment.

haxepunk/HXP.hx, haxepunk/graphics/BaseEmitter.hx, haxepunk/graphics/BitmapText.hx, haxepunk/graphics/NineSlice.hx, haxepunk/graphics/Text.hx, haxepunk/graphics/Tilemap.hx, haxepunk/graphics/atlas/Atlas.hx, haxepunk/graphics/atlas/AtlasData.hx, haxepunk/graphics/atlas/AtlasRegion.hx, haxepunk/graphics/atlas/AtlasResolutions.hx, haxepunk/graphics/atlas/DrawCommand.hx, haxepunk/graphics/atlas/HardwareRenderer.hx, haxepunk/graphics/atlas/IAtlasRegion.hx, haxepunk/graphics/atlas/Renderer.hx, haxepunk/screen/ScaleMode.hx, haxepunk/screen/UniformScaleMode.hx, haxepunk/utils/Platform.hx
=> Use BitmapText format tags to move/shake characters.

haxepunk/graphics/Graphiclist.hx, haxepunk/graphics/atlas/FrameBuffer.hx, haxepunk/graphics/atlas/GLUtils.hx, haxepunk/graphics/atlas/HardwareRenderer.hx, haxepunk/graphics/atlas/SceneSprite.hx, haxepunk/graphics/shaders/ColorShader.hx, haxepunk/graphics/shaders/Shader.hx, haxepunk/graphics/shaders/TextureShader.hx, include.xml, tests/test-nme.hxml, tests/test-openfl3.hxml, tests/test-openfl4.hxml
Alternative to https://github.com/HaxePunk/HaxePunk/pull/479 that doesn't allocate extra Camera objects
=> Graphiclist fix (fixes #479)

haxepunk/Engine.hx, haxepunk/math/Vector2.hx, haxepunk/utils/Draw.hx
This is a hardware replacement for the Draw class. It supports curves, circles, rectangles, and polylines. The lines can have beveled or mitered edges.
At the moment it draws in world space. This might make more sense as a Shape graphic class.
=> Hardware Draw

haxepunk/Entity.hx, haxepunk/Graphic.hx, haxepunk/Scene.hx, haxepunk/graphics/shader/Shader.hx, tests/src/haxepunk/EntityTest.hx, tests/test-nme.hxml, tests/test-openfl3.hxml, tests/test-openfl4.hxml, tests/test-openfl5.hxml
I'm adding unit tests for Entity and found some inconsistencies in setting x/y out of order. I'm assuming this is not intended but I may be missing something.
=> Entity tests

haxepunk/Entity.hx
=> Clarified "layer" definition

haxepunk/Engine.hx, haxepunk/Graphic.hx, haxepunk/HXP.hx, haxepunk/debug/Console.hx, haxepunk/graphics/Image.hx, haxepunk/graphics/NineSlice.hx, haxepunk/graphics/Spritemap.hx, haxepunk/graphics/atlas/Atlas.hx, haxepunk/graphics/atlas/AtlasData.hx, haxepunk/graphics/atlas/AtlasRegion.hx, haxepunk/graphics/atlas/AtlasResolutions.hx, haxepunk/graphics/atlas/IAtlasRegion.hx, haxepunk/graphics/atlas/TextureAtlas.hx, haxepunk/graphics/hardware/DrawCommand.hx, haxepunk/graphics/hardware/DrawCommandBatch.hx, haxepunk/graphics/text/GlyphData.hx, haxepunk/graphics/text/Text.hx, haxepunk/graphics/tile/TiledImage.hx, haxepunk/graphics/tile/Tilemap.hx, haxepunk/masks/Grid.hx, haxepunk/masks/Imagemask.hx, haxepunk/masks/Pixelmask.hx, haxepunk/masks/SlopedGrid.hx, haxepunk/math/Rectangle.hx, haxepunk/math/Vector2.hx, tests/src/haxepunk/math/RectangleTest.hx
Another step to move away from the Flash API. I created a Rectangle class that meets the needs of HaxePunk.
=> Using internal Rectangle class

examples/asteroids/assets/shaders/pixel.frag, examples/asteroids/src/Main.hx, examples/asteroids/src/asteroids/entities/Asteroid.hx, examples/asteroids/src/asteroids/entities/ExplodingEntity.hx, examples/asteroids/src/asteroids/entities/Ship.hx, examples/asteroids/src/asteroids/graphics/CircularMeter.hx, examples/asteroids/src/asteroids/scenes/MainScene.hx, examples/asteroids/src/asteroids/scenes/import.hx
=> Update Asteroids example

haxepunk/input/gamepad/ControllerData.hx
A controller with no buttons would generate an empty array instead of an empty map.
=> Fixed empty button mappings compilation error

haxepunk/graphics/hardware/opengl/GLUtils.hx
This operation is slow for mobile browsers
=> Wrap GL.getError

tests/src/haxepunk/CameraTest.hx
Added a basic test file for the camera to confirm that anchor works as expected.
=> Add camera test

haxepunk/input/Gamepad.hx
Useful for testing buttons, or features which need to test any button.
What do you think? There are probably more functions I can add, perhaps allocating an array each time should instead have an array passed in?
=> Additional Polling functions for Gamepad
