com/haxepunk/Screen.hx

Referencing this problem: http://forum.haxepunk.com/index.php?board=4.0
HXP.screen.fillRect for HTML5 uses ARGB, so HXP.stage.color ends up not having the correct alpha values.

Fixed screen not clearing on HTML5 target

---

com/haxepunk/HXP.hx

According to documentation:
"static tween (object : Dynamic, values : Dynamic, duration : Float, ?options : Dynamic) : MultiVarTween
Tweens numeric public properties of an Object. Shorthand for creating a MultiVarTween tween, **starting it** and adding it to a Tweener."
But tweener.addTween needs start=true for that to happens:
HaxePunk/com/haxepunk/Tweener.hx
public function addTween(t:Tween, start:Bool = false):Tween
It is already corrected in HXP.alarm:
tweener.addTween(alarm, true);
But not corrected in HXP.tween:
tweener.addTween(tween);
so I believe it needs to chage to this in order to be compatible with the documentation:
tweener.addTween(tween, true);

HXP.tween doesn't start the tween automatically

---

.travis.yml
Makefile
com/haxepunk/Preloader.hx
com/haxepunk/graphics/atlas/AtlasData.hx
com/haxepunk/graphics/atlas/Renderer.hx
com/haxepunk/graphics/atlas/Tilesheet.hx
com/haxepunk/graphics/atlas/renderer/DrawTilesRenderer.hx
com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx
doc/Main.hx
haxelib.json
include.xml
tests/compile.hxml

Still needs polish but submitting now so people can try this out. Adds an OpenGL implementation of drawTiles which falls back to drawTiles if it exists (on NME or older OpenFL versions)
To test,
- install the latest OpenFL and Lime
- check out the feature branch on my fork
- ~~for now you need to compile with `-Dtile_shader -DnoHaxepunkPreloader` to use the TileShaderRenderer~~ special flags no longer needed
Please let me know if you notice any discrepancies.
TODO:

Add TileShaderRenderer for OpenFL 4 support.

---

com/haxepunk/HXP.hx
com/haxepunk/Scene.hx
com/haxepunk/utils/Cursor.hx
com/haxepunk/utils/Input.hx

As a contribution for the next release, I added a custom entity that follows the cursor around and also hides the original cursor.
This can be accessed through the function setCursor inside the Scene class. I thought of making it apply to every scene, however I felt it was a little bit too intrusive, since I would have to modify classes that don't have anything to do with that sort of procedure, such as HXP, for example.
Anyways, the function receives a Cursor object and automatically sets the layer as the highest it can be, so it is rendered above everything. However, as an exception, if the layer is already modified, this will not happen, as it would imply the user wants the mouse to be at a particular layer, and not above everything else.
Feedback is greatly appreciated, specially …

Added custom cursor support

---

com/haxepunk/graphics/atlas/renderer/TileShaderRenderer.hx

There is a small type error in the new `TileShaderRenderer` code. I got the following error when running the dev branch:
```
.../graphics/atlas/renderer/TileShaderRenderer.hx:212: characters 57-108 : Array<Float> should be lime.utils.Float32Array
.../graphics/atlas/renderer/TileShaderRenderer.hx:212: characters 57-108 : For function argument 'v'
```
Refering to the 3th argument of this line
```
gl.uniformMatrix4fv(shader.data.uMatrix.index, false, renderer.getMatrix(displayObject.__renderTransform));
```
The called function is `GLRenderer.getMatrix(transform:Matrix4):Array<Float>`.
I'm not sure if this small fix is the most optimal, performance wise.

Fix TileShaderRenderer: convert Array<Float> to lime.utils.Float32Array

---

com/haxepunk/graphics/Text.hx

Updating attributes off of Text doesn't always refresh the graphic.
So this gives people to option to call it manually to refresh text.

Changed updateTextBuffer to public

---

template/src/{{PROJECT_CLASS}}.hx

The static main function isn't needed because it is provided by openfl. It also doesn't compile with Haxe 3.4.2 as it currently is.
EDIT: I think at one point this was required for neko but it doesn't appear to be an issue now.

Removing static main function (openfl provides)

---

haxepunk/graphics/atlas/DrawCommandBatch.hx

I was migrating an old project to HaxePunk 4.0 and noticed that the texture offsets looked weird. There was an extra pixel on the right and bottom of the sprite. Since OpenGL seems to require half pixel offsets (texel weirdness) I assumed that it was because the uvx2 and uvy2 values were adding instead of subtracting. However, when I changed it to subtraction I noticed that a half pixel on all sides were getting chopped when scaled. It seems that OpenGL isn't using half pixel offsets any more or this is being handled farther down in the HaxePunk/OpenFL code.
Here is an example of the before (top) and after.
I am testing on an iMac 2011 Using macOS 10.12.4

Half Pixel Offset

---

haxepunk/debug/Console.hx

This was necessary at some point but the ENTER_FRAME callback renders the scene regardless of whether the console is shown. Calling it here results in double counting the FPS.
Assigning @MattTuttle if you want to take a look, otherwise kick it back to me.
Fixes #454

Debug console doesn't need to handle rendering anymore.

---

haxepunk/Entity.hx
haxepunk/Graphic.hx
haxepunk/ds/Either.hx
haxepunk/ds/OneOf.hx
haxepunk/graphics/Backdrop.hx
haxepunk/graphics/Emitter.hx
haxepunk/graphics/Image.hx
haxepunk/graphics/Spritemap.hx
haxepunk/graphics/Tilemap.hx
haxepunk/input/Input.hx

Simplifies SolidType and InputType using the OneOf class. I also removed the `type` variable from the graphics classes and make the "from" methods cleaner.
This results in cleaner code generation but could impact external code if someone is using the abstract types.

Refactoring abstract classes to use haxe.ds.Either

---

haxepunk/HXP.hx
haxepunk/graphics/BitmapText.hx
haxepunk/graphics/atlas/BitmapFontAtlas.hx
haxepunk/graphics/atlas/TextureAtlas.hx

BitmapText can define format markup tags which affect a subset of the text as well as custom image tags which are rendered inline with the text. Also added a `displayCharCount` for gradually revealed text.
```
BitmapText.defineFormatTag("green", 0x55d400);
BitmapText.defineFormatTag("blue", 0x5f8dd3);
BitmapText.defineImageTag("my-img", new Image("assets/graphics/testimage.png"));
var txt = new BitmapText("Supports <green>colored</green> <blue>text</blue> and images: <my-img/>", 0, 0, 0, 0, {font: 'assets/fonts/myfont.fnt', size: 16});
```
TODO:

Rich BitmapText

---

haxepunk/HXP.hx

Benchmarked this locally and the pop method takes 50x as long for an array of 256 ints. Since this method is very unlikely to be taking significant amounts of CPU time (time to clear an array of 256 ints on my laptop was 2.64637470245361e-06 seconds) and this eliminates the extra array allocations, I think this is a good tradeoff until Haxe provides a saner way of clearing arrays.
For reference, HaxeFlixel is using pop to clear arrays too: https://github.com/HaxeFlixel/flixel/blob/master/flixel/util/FlxArrayUtil.hx#L93. Since the ratio of pop time / splice time gets worse as the size of the array gets larger, I think the heuristic makes sense.

Reduce GC from HXP.clear.

---

haxepunk/Graphic.hx
haxepunk/graphics/Backdrop.hx
haxepunk/graphics/BaseEmitter.hx
haxepunk/graphics/BitmapText.hx
haxepunk/graphics/Image.hx
haxepunk/graphics/Tilemap.hx

Graphic should set smooth and color defaults instead of in descendants. Haxe set functions aren't called when properties have default values which is why I moved the color assignment to the constructor.

Adding default values to Graphic constructor

---

haxepunk/graphics/Backdrop.hx
haxepunk/graphics/BitmapText.hx
haxepunk/graphics/Image.hx
haxepunk/graphics/TiledImage.hx
haxepunk/graphics/TiledSpritemap.hx
haxepunk/graphics/Tilemap.hx
haxepunk/graphics/atlas/Atlas.hx
haxepunk/graphics/atlas/AtlasData.hx
haxepunk/graphics/atlas/AtlasRegion.hx
haxepunk/graphics/atlas/AtlasResolutions.hx
haxepunk/graphics/atlas/IAtlasRegion.hx

The place that the new `shader` argument shows up in the various rendering functions is inconsistent (sometimes first, sometimes after layer.) This updates them all to follow the order DrawCommand uses - all of the args that determine which DrawCommand to use (shader, smooth, blend, clipRect) always appear together in the same order.

Shader argument order consistency.

---

haxepunk/graphics/Spritemap.hx

The C++ target having initialized the `frame` value to 0, line 102 did not refresh the _region object, which then remained null until the frame was set again, thus resulting in a null pointer exception (somehow, not reported ?) and a silent crash everytime the _region object was used (this includes render() and get_width() / get_height()). Initializing `frame` to -1 fixed this crash.

Fixed C++ crash on most accesses to Spritemap

---

haxepunk/Engine.hx
haxepunk/Scene.hx
haxepunk/Tween.hx
haxepunk/Tweener.hx
haxepunk/tweens/misc/AngleTween.hx
haxepunk/tweens/misc/ColorTween.hx
haxepunk/tweens/misc/MultiVarTween.hx
haxepunk/tweens/misc/NumTween.hx
haxepunk/tweens/misc/VarTween.hx
haxepunk/tweens/motion/CircularMotion.hx
haxepunk/tweens/motion/CubicMotion.hx
haxepunk/tweens/motion/LinearMotion.hx
haxepunk/tweens/motion/LinearPath.hx
haxepunk/tweens/motion/QuadMotion.hx
haxepunk/tweens/motion/QuadPath.hx
haxepunk/tweens/sound/Fader.hx
haxepunk/tweens/sound/SfxFader.hx
tests/src/haxepunk/TweenTest.hx
tests/src/haxepunk/TweenerTest.hx
tests/src/haxepunk/tweens/misc/MultiVarTweenTest.hx
tests/src/haxepunk/tweens/misc/VarTweenTest.hx

I added unit tests for the var Tweens and Tweener class. The update function now explicitly takes an elapsed parameter instead of using it from HXP.elapsed. I felt this code was buried and it makes the unit tests cleaner.
This also found an issue with Tweener.clearTweens that is resolved.

More Tween unit tests

---

haxepunk/HXP.hx

The previous code would write to the cache and delete it instantly after, also removeBitmap would always return true as bitmapAdded had just been added.

Fixed an issue on overwriteBitmapCache

---

haxepunk/Camera.hx
haxepunk/Cursor.hx
haxepunk/Entity.hx
haxepunk/Scene.hx
haxepunk/debug/Console.hx

Entity is no longer coupled to the scene camera. This moves us in the right direction of using multiple cameras. `Entity.followCamera` is now used to select the camera you wish to follow with this entity.

Removing scene camera from Entity and passing it on render()

---

haxepunk/Graphic.hx
haxepunk/graphics/ColoredRect.hx
haxepunk/graphics/hardware/DrawCommand.hx
haxepunk/graphics/hardware/DrawCommandBatch.hx
haxepunk/graphics/hardware/HardwareRenderer.hx
haxepunk/utils/DrawContext.hx

BlendMode was defaulting to Add instead of Alpha with the change to an abstract class. Also, when Texture was null it would keep creating a new DrawCommand instance so I'm using `Texture.nullTexture`.

Fixing blend mode default and null texture check

---

haxepunk/graphics/shader/Shader.hx

This change allows for addition of new vertex attributes when overriding the base Shader class.

Allow for extra vertex attribs in child shader classes

---

examples/HXPBunnies/src/scenes/GameScene.hx

**Problem:** The bunny add function was being called before the overlay text was initialized, therefore using a null value, causing an unexpected(and silent) crash.
**Solution:**
Simply moved the addBunnies function below the overlayText.
**Extra:**
- Made sure the pirate was a layer infront of bunnies
- Gave the overlay entity a layer of -1000 to prevent being covered.
- Removed unnecessary bunny count trace for console

BunnyMark OverlayText Fix

---

haxepunk/graphics/hardware/RenderBuffer.hx
haxepunk/graphics/shader/Shader.hx
haxepunk/graphics/shader/TextureShader.hx

Right now one can set custom vertex attributes of 1 to 4 floats (float, vec2, vec3, vec4 ; basically what the OpenGL specification allows). This should eventually be expanded (especially uniforms, really) into being able to set custom vertex attributes of all possible types.

Custom vertex attributes

---

haxepunk/HXP.hx
haxepunk/graphics/atlas/AtlasData.hx
haxepunk/graphics/atlas/AtlasRegion.hx

This is a tiny pull request compared to the last two!
I found that calculating the 90 degree rotated matrix is super fast when you know cos = 0 and sin = 1.
There are still 3 references to Matrix in Text, Imagemask, and Screen. I'm thinking those classes are going to need significant changes or will be lime/nme only.

Remove reference to flash.geom.Matrix where possible

---

haxepunk/graphics/shader/Shader.hx

This fixes an issue that could happen when an attribute's data is changed to an array smaller than was previously in place.

Reset attribute data position upon data change

---

haxepunk/Entity.hx

Fixes a browser platform specific problem(#514) with respect to Std.int
not throwing errors but instead overriding all passed in defaultValue(s)
to zero. This was causing problems for origin x/y being incorrectly
overwritten.
Reflect.hasField could have been used but is only expected to work for
anonymous structures.
- Removed Flash gaurd
- Fixed(?) base git issues

Fixed setHitboxTo for HTML5

---

haxepunk/graphics/atlas/TileAtlas.hx
haxepunk/graphics/tile/Tilemap.hx

This pull addresses the issue outlined in #538.
I couldn't think of any reason that Tilemap should assume that TileAtlas is a gridded tileset with it's origin at (0,0) instead of simply using the regions defined in the atlas.
**Change overview.**
* Moved _tileWidth and _tileHeight from Tilemap to TileAtlas.
* Removed _setCount, _setRows, _setColumns and _tile from Tilemap.
* Changed Tilemap.drawTile() uses data from the AtlasRegion instead of _tile.
**Public API changes:**
* Removed updateTileRect(), getIndex(), getX() and getY() from Tilemap.

Fix for #538

---

haxepunk/graphics/hardware/DrawCommand.hx
haxepunk/graphics/shader/Shader.hx

Every triangle, even those off-screen, need to be drawn if a shader has custom vertex attributes, or else the vertex attrib pointers would not be advanced properly.

Fixed triangle screen check breaking shader with custom vertex attributes

---

.travis.yml

This fixes the TravisCI build error here: https://travis-ci.org/HaxePunk/HaxePunk/jobs/339100650#L572
I'm not sure how safe it is to use the bleeding edge version number though.

Updated NME version for TravisCI.

---

.travis.yml
backend/flash/haxepunk/_internal/TouchInput.hx
examples/asteroids/src/Ship.hx
haxepunk/Camera.hx
haxepunk/Engine.hx
haxepunk/HXP.hx
haxepunk/Screen.hx
haxepunk/cameras/UICamera.hx
haxepunk/graphics/text/BitmapText.hx
haxepunk/screen/FixedHeightScaleMode.hx
haxepunk/screen/FixedScaleMode.hx
haxepunk/screen/ScaleMode.hx
haxepunk/screen/UniformScaleMode.hx
tests/src/haxepunk/ScreenTest.hx
tests/src/haxepunk/screen/UniformScaleModeTest.hx

* Removing `Screen.scale` and subsequently `Screen.fullScaleX` and `Screen.fullScaleY`
* Moving `Screen.shake()` to `Camera`. This allows UI scenes that don't shake.
* Moving `Screen.needsResize` to `HXP`

Screen cleanup

---

backend/flash/haxepunk/graphics/text/Text.hx

Besides making the codebase more consistent with how it handles warnings, this also fixes #556

Update Text.hx to use Log functions for warnings instead of in-game console

---

haxepunk/utils/Log.hx

When running a game in Neko with the debug flag, the game would immediately crash due to invalid field access in `haxe.Log.trace`. Looks like this was because the Haxe library's current implementation of `trace` on Neko didn't handle cases where the PosInfos parameter was null. This PR fixes the Log.hx class so that Neko projects can run and log correctly in debug mode.

Fixed instant crash on Neko -debug

---

MIGRATION.md

"Backdrop" was spelled "Backdro"

Corrected missing character in Migration.md

---

haxepunk/Position.hx

Fixes the problem from #566 where Entities were not converted to Positions when passed as parameters to MathUtil functions. This PR also removes an unnecessary `fromObject()` method from the Position class and adds documentation for the helper structs in `Position.hx` for future reference.

Entity now implicitly casts to Position

---

haxepunk/HXP.hx
haxepunk/tweens/misc/Alarm.hx

Not sure why this was taken out since `Tween` still implements it and the documentation still mentionned it.

Add `callback` parameter to Alarm

---

haxepunk/Engine.hx

Under very specific circumstances, Engine could render a scene before its `begin()` method was called.

Do not render unready scenes

---

tools/Project.hx
tools/Run.hx

This will fix any issues in the inital "run" from haxelib, on any OS, where the template folder needs to be compressed into a zip file. The original implementation relied on external dependencies like "make" and "zip" which some OS's (many window variants) don't have.
You can see the original make call has been replaced with a `haxe.zip` implementation.
The `getEntries` function is exactly the one found in the haxe cookbook: https://code.haxe.org/category/other/haxe-zip.html
**Run.hx**: Added the OS agnostic template compression.
**Project.hx**: Since this never worked on windows, the line I added was to fix a small bug that was never come across.

Solution for projects on Windows

---

.github/CONTRIBUTING.md

This update should now help people avoid any unnecessary work and provide the necessary info to begin performing HaxePunk unit tests.
This fix addresses #613

Update testing documentation

---

haxepunk/Scene.hx

Scene functions that retrieve entities in arrays or list should return an empty container of whatever they type they return instead of null for consistency's sake.

Updated Scene to return empty containers
